---
- hosts: default
  become: true

  tasks:
    - name: update apt 
      apt:
        update_cache: yes
    
    - name: Install java runtime environment
      apt:
        name: default-jre
        state: present

    - name: Add apt signing key to keyring file
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
        
    - name: Install apt transport
      apt:
        name: apt-transport-https
        state: present

    - name: Add APT repository
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/8.x/apt stable main
        state: present
        filename: elastic-8.x.list
        update_cache: yes

    - name: Install {{ stack }}
      apt:
        name: "{{ stack }}"
        update_cache: yes

    # - name: Download Elastic Deb Package
    #   get_url:
    #     url: https://artifacts.elastic.co/downloads/{{ stack }}/{{ stack }}-8.3.3-amd64.deb
    #     dest: /tmp

    # - name: Install Elastic Deb Package
    #   apt:
    #     deb: /tmp/{{ stack }}-8.3.3-amd64.deb
      
    - name: Enable {{ stack }} service
      service:
        name: "{{ stack }}"
        enabled: yes
        daemon_reload: yes
        
    - name: Start {{ stack }} service
      service:
        name: "{{ stack }}"
        state: started
        
