---
- hosts: default
  become: true

  tasks:
    - name: update apt cache if needed
      apt:
        update_cache: yes

    - name: Install Java Runtime Environment 
      apt:
       name: default-jre
       state: present
    
    - name: Download Filebeat Package
      get_url:
        url: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.17.6-amd64.deb
        dest: /tmp
    
    - name: Install FileBeat Deb Package
      apt:
        deb: /tmp/filebeat-7.17.6-amd64.deb
    
    # - name: Remove FileBeat YAML File
    #   file:
    #     path: /etc/filebeat/filebeat.yml
    #     state: absent
    
    # - name: Create New FileBeat YAML File
    #   file:
    #      path: /etc/filebeat/filebeat.yml
    #      state: touch

    # - name: Add FileBeat YAML Configuration
    #   blockinfile:
    #      path: /etc/filebeat/filebeat.yml
    #      marker: ""
    #      block: |
    #        filebeat.inputs:
    #        - type: log
    #          paths:
    #           - /var/log/*.log
    #        output.logstash:
    #           hosts: ["pri_ip_logstash:5044"]
    
    - name: Start FileBeat Service
      service:
        name: filebeat
        state: started
    
    # - name: Download Metricbeat Package
    #   get_url:
    #     url: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-8.3.3-amd64.deb
    #     dest: /tmp
    
    # - name: Install Metricbeat Deb Package
    #   apt:
    #     deb: /tmp/metricbeat-8.3.3-amd64.deb

    # - name: Start Metricbeat Service
    #   service:
    #     name: metricbeat
    #     state: started