---
- hosts: default
  gather_facts: yes
  become: true

  pre_tasks:
    - name: update apt cache if needed
      apt:
        update_cache=yes
        cache_valid_time=3600

  tasks:
    - name: Install Java Runtime Environment 
      apt:
        name: default-jre
        state: present

    - name: Download Kibana Deb Package
      get_url:
        url: https://artifacts.elastic.co/downloads/kibana/kibana-8.3.3-amd64.deb
        dest: /tmp

    - name: Install Kibana Deb Package
      apt:
        deb: /tmp/kibana-8.3.3-amd64.deb
    
    - name: Update Kibana Config (IP address)
      lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: 'server.host'
        line: 'server.host: 0.0.0.0'
    
    - name: Update Kibana Config (Kibana Port)
      lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: 'server.port'
        line: 'server.port: 5601'
    
    - name: Update Kibana Config (Kibana URL)
      lineinfile:
        destfile: /etc/kibana/kibana.yml
        regexp: 'elasticsearch.hosts'
        line: 'elasticsearch.hosts: ["http://pri_ip_es:9200"]'
    
    - name: Start Kibana Service
      service:
        name: kibana
        state: started