---
- hosts: default
  gather_facts: yes

  pre_tasks:
    - name: update apt cache if needed
      become: yes
      apt:
        update_cache=yes
        cache_valid_time=3600

  tasks:
    - name: Install Java Runtime Environment 
      become: yes
      apt:
       name: default-jre
       state: present

    - name: Download Logstash Deb Package
      get_url:
        url: https://artifacts.elastic.co/downloads/logstash/logstash-7.6.2.deb
        dest: /tmp
    
    - name: Install Logstash Deb Package
      become: yes
      apt:
        deb: /tmp/logstash-7.6.2.deb

    - name: Create Logstash Pipeline File
      become: yes
      file:
         path: /etc/logstash/conf.d/main.conf
         state: touch

    - name: Add Logstash Pipeline Configuration
      become: yes
      blockinfile:
         path: /etc/logstash/conf.d/main.conf
         marker: ""
         block: |
           input {
             file {
              path => "//pri_ip_filebeat/e$/*.log"
             start_position => "beginning"
             }
           }
           output {
             elasticsearch { hosts => ["pri_ip_es:9200"]
             }
           }
    
    - name: Start Logstash Service
      become: yes
      service:
        name: logstash
        state: started